// Code generated by goctl. DO NOT EDIT!
// Source: inbox.proto

package server

import (
	"context"
	"inbox/rpc/inbox"
	"inbox/rpc/internal/logic"
	"inbox/rpc/internal/svc"
)

type InboxServer struct {
	svcCtx *svc.ServiceContext
}

func NewInboxServer(svcCtx *svc.ServiceContext) *InboxServer {
	return &InboxServer{
		svcCtx: svcCtx,
	}
}

func (s *InboxServer) Ping(ctx context.Context, in *inbox.Request) (*inbox.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
